apiVersion: skaffold/v4beta7
metadata:
  name: computesdk
kind: Config
build:
  artifacts:
    - image: computesdk-gateway
      context: .
      docker:
        dockerfile: cmd/gateway/Dockerfile
      sync:
        manual:
          - src: 'cmd/**/*.go'
            dest: '.'
          - src: 'pkg/**/*.go'
            dest: '.'
          - src: 'go.mod'
            dest: '.'
          - src: 'go.sum'
            dest: '.'
    - image: computesdk-api
      context: .
      docker:
        dockerfile: cmd/api/Dockerfile
      sync:
        manual:
          - src: 'cmd/**/*.go'
            dest: '.'
          - src: 'pkg/**/*.go'
            dest: '.'
          - src: 'go.mod'
            dest: '.'
          - src: 'go.sum'
            dest: '.'
  # For local development (OrbStack/minikube)
  local:
    push: false
  # For EKS/cloud deployment, uncomment and set your registry:
  # tagPolicy:
  #   gitCommit: {}
  # To use with EKS, run:
  # skaffold run --default-repo=YOUR_ECR_REPO

deploy:
  # Only deploy Postgres operator (essential for API keys)
  helm:
    releases:
      # Postgres operator
      - name: zalando-postgres-operator
        repo: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
        remoteChart: postgres-operator
        namespace: operators
        valuesFiles:
          - deployments/operators/postgres-operator/zalando-values-local.yaml

  # Core services using kubectl
  kubectl: {}

# Define the raw YAML manifests to be rendered
manifests:
  rawYaml:
    - deployments/namespaces.yaml
    - deployments/ingress.yaml
    - deployments/rbac/*.yaml
    - deployments/gateway/*.yaml
    - deployments/api/api-deployment.yaml
    - deployments/api/api-service.yaml
    - deployments/postgres/*.yaml