# Prometheus Operator values for local development

# Default values are fine for most settings, this configuration
# focuses on adapting Prometheus Operator to work in a local
# development environment with reduced resource requirements.

# Global settings
global:
  rbac:
    create: true
  
# Prometheus configuration
prometheus:
  enabled: true
  serviceMonitorSelector: {}
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelectorNilUsesHelmValues: false
  
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"

# Alertmanager configuration
alertmanager:
  enabled: true
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "100m"

# Grafana configuration
grafana:
  enabled: true
  adminPassword: admin
  service:
    type: ClusterIP
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "100m"
  
  # Persistence for Grafana
  persistence:
    enabled: false

# Disable features not needed for local development
kubeControllerManager:
  enabled: false
  
kubeEtcd:
  enabled: false

kubeScheduler:
  enabled: false

# Node exporter for collecting system metrics
nodeExporter:
  enabled: true
  
# kube-state-metrics for Kubernetes object metrics
kubeStateMetrics:
  enabled: true
  
prometheusOperator:
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "100m"

# Disable Thanos which is used for scale-out Prometheus
thanosRuler:
  enabled: false
